name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: conda-forge,defaults
        channel-priority: strict
    
    - name: Create conda environment
      shell: bash -l {0}
      run: |
        conda create -n contextualforget python=${{ matrix.python-version }} -y
        conda activate contextualforget
        pip install -U pip
        pip install -e ".[dev]"
    
    - name: Run tests
      shell: bash -l {0}
      run: |
        conda activate contextualforget
        pytest tests/ -v --tb=short
    
    - name: Run basic linting (check only)
      shell: bash -l {0}
      run: |
        conda activate contextualforget
        ruff check src/ --select F,E,W --ignore UP035,UP006,UP045,PTH123,PTH202,PTH108,PTH103,B019,B905,C405,TC002,I001 || true
        echo "Linting completed with warnings (non-blocking)"
  
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        channels: conda-forge,defaults
        channel-priority: strict
    
    - name: Create conda environment and build
      shell: bash -l {0}
      run: |
        conda create -n contextualforget python=3.11 -y
        conda activate contextualforget
        pip install -U pip
        pip install -e ".[dev]"
        pip install build
        python -m build
  
  integration-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        channels: conda-forge,defaults
        channel-priority: strict
    
    - name: Create conda environment and run integration tests
      shell: bash -l {0}
      run: |
        conda create -n contextualforget python=3.11 -y
        conda activate contextualforget
        pip install -U pip
        pip install -e ".[dev]"
        make data
        make ingest_ifc
        make ingest_bcf
        make link
        make build_graph
        make query