name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m venv .venv && . .venv/bin/activate && pip install -e .[dev]
      - run: . .venv/bin/activate && ruff --version && ruff check .
      - run: . .venv/bin/activate && pytest -q
